[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'hdima/python-syntax'
on_ft = 'python'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
