[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugin]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim', 'vim-textobj-user', 'quickrun.vim']
