[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'vim-fugitive'
hook_add = 'call coil398#init#lightline#hook_add()'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = 'call coil398#init#gtags#hook_add()'

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = 'let g:gen_tags#gtags_auto_gen = 1'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
